### ISSUE TITLE
Wording in the article

### ISSUE THREAD

**Issue by hmroczek** [AdobeDocs/analytics.en#215]
Issue in ./help/components/dimensions/prop.md

The customer is complaining that the warning in the section "Case Sensitivity" is insufficient to understand the consequences of toggling the case sensitivity option. 

Could you please consider changing it so it gives more information and warning to customers of what potential results are of toggling this feature?

**Comment by gigazelle** [comment]
I would prefer to keep the succinct wording of that message as-is, because the intricacies of toggling this setting aren't really relevant to a wide audience. The important thing to know is that you're not going to see consistent results when looking at data that spans the date that you toggle this setting.

However since you asked here I'm happy to spill _all_ the beans. Consider the following example:

1. A visitor arrives at your site at the beginning of the month, and uses internal search.
1. They search for the following three terms consecutively: `Dog`, `DOG`, and `dog`. Search terms are collected in a prop as separate page views.
1. You pull a mid-month report to see internal search keywords to date.
1. Following this report, you contact Customer Care and have them toggle 'Ignore Case'.
1. Later on in the month, the visitor comes back and performs the same three internal searches: `Dog`, `DOG`, and `dog`.
1. You pull another report at the end of the month that contains both of the above visits.

If going from 'ignore case' to 'case sensitive', the mid-month report would look like this:

prop1 | page views
--- | ---
`Dog` | 3

Analytics uses the first case collected in the calendar month. Then you make it case sensitive and pull the end of month report:

prop1 | page views
--- | ---
`Dog` | 4
`Dog` | 1
`DOG` | 1

On the Adobe Analytics back end, the values that ignore case are treated as if they are all lowercase. However, the displayed case is still the value originally used when 'Ignore Case' was enabled. The resulting report is two 'Dog' line items that appear identical.

Now, if going from 'case sensitive' to 'ignore case', it's a bit more straightforward:

Mid-month report:

prop1 | page views
--- | ---
`Dog` | 1
`DOG` | 1
`dog` | 1

End of month report:

prop1 | page views
--- | ---
`dog` | 4
`DOG` | 1
`Dog` | 1

Values set to ignore case are treated as if they are all lowercase. The all-lowercase value previously collected is combined with the 'Ignore Case' values.

It's also worth noting that if you have existing filters or segments that rely on prop values, you'll want to double check that they still work because they might be using a value with a different case.

Hopefully this gives you everything you need around this topic. If you have any suggestions around how to make that warning communicate this word dump while still being succinct, I'm open to updating it as well.
