### ISSUE TITLE
Documentation claims 2.0 APIs include all 1.4 API capabilities despite removing interactions with Classifications

### ISSUE THREAD

**Issue by dbrakman** [AdobeDocs/analytics.en#292]
Issue in ./help/admin/c-admin-api/c-admin-14-api-eol.md:

Documentation claims "Any capabilities that are available in the 1.4 APIs can be accomplished using the [Adobe Analytics 2.0 APIs](https://developer.adobe.com/analytics-apis/docs/2.0/)", but there are no 2.0 API methods that provide the functionality of the 1.4 APIs Classifications.CreateExport, Classifications.GetStatus, and Classifications.GetExport to get SAINT classifications.
<img width="1279" alt="image" src="https://github.com/user-attachments/assets/0131117c-1c8c-4900-9774-eeed5900b44e">
<img width="1241" alt="image" src="https://github.com/user-attachments/assets/1d230ebc-9778-4b4f-b212-70e5df5467b4">

**Comment by dbrakman** [comment]
The Endpoint Guides at <https://developer.adobe.com/analytics-apis/docs/2.0/guides/endpoints/> say to see that [that](https://developer.adobe.com/analytics-apis/docs/2.0/apis/) "API reference for a full list of calls that you can make" despite describing Classifications endpoints not on that full list

![image](https://github.com/user-attachments/assets/afb10315-849a-43ce-a71b-b04a0c0c8cfe)

**Comment by johnwight** [comment]
@dbrakman thank you for pointing this issue out. Regarding the issue of "any capability in 1.4 being possible in 2.0," my understanding is that it does not mean there is a 1:1 equivalent for API functions, but an end objective in 1.4 is possible in 2.0 with a different methodology. Beyond that I will ask the developer to respond to the issue for perhaps more clarification. It might be helpful if he were to know what your classifications goal is above the level of individual endpoints. I'll try to get him to answer directly.

Regarding, any missing endpoints in the 2.0 swagger reference, It is not easy to navigate the names of these endpoints between the two. The endpoint guide is currently meant to have friendlier names. Can you please indicate which 2.0 APIs described in the endpoint guide that you do not see in the reference? I will forward that directly to the developer. Thanks again for this issue.

**Comment by johnwight** [comment]
@dbrakman Thanks for your patience in getting answers for your questions. I've received responses to your questions from the developer and summarized them in one our [1.4 to 2.0 API Migration](https://developer.adobe.com/analytics-apis/docs/2.0/guides/migration/#classifications) guides for further reference to you and other users (so thanks for your questions). I've also included the developer's direct comments below:
_________
* `Classifications.CreateExport` in API 1.4 is used for creating one export job. In API 2.0, it is replaced by * `[/classifications/job/export/{DATASET_ID}]
* 
`Classifications.GetStatus` in API 1.4 is used for getting one import or export job status. In API 2.0, it is replaced by [/classifications/job/{JOB_ID}]
* `Classifications.GetExport` in API 1.4 is for downloading the export classification data. In API 2.0, there are two endpoints for download the export classification file (data):
Step1: [/classifications/job/export/file/{JOB_ID}/list](https://developer.adobe.com/analytics-apis/docs/2.0/guides/endpoints/classifications/#get-classification-job-file-partition-list) , retrieve a list of file parts of export file
Step2: [/classifications/job/export/file/{JOB_ID}/{FILE_NAME}](https://developer.adobe.com/analytics-apis/docs/2.0/guides/endpoints/classifications/#get-classification-export-job-file-part), retrieve a part of a complete classification data file

SAINT is still in use by a few customers, as we haven't fully migrated all Analytics customers to the new Classification system. Some customers don't have an IMS org ID, and others have very large and frequent classification imports, which pose challenges for downstream components like Oberon. I haven't heard of a clear decommission date for API 1.4 yet; it might happen sometime next year.

_______________________________________________________

Hopefully this answers your question. If not, please respond. Otherwise I will close the issue after a period of time. Thanks again.
