### ISSUE TITLE
Default Date Range

### ISSUE THREAD

**Issue by adobeewright** [AdobeDocs/analytics.en#81]
Issue in help/analyze/analysis-workspace/components/calendar-date-ranges/calendar.md

I just want to verify that the Default Date Range in Analysis Workspace Panel is This Month.

**Comment by gigazelle** [comment]
Thank you for the report! Since this is the page around the calendar selector and not Workspace, the documentation is correct in that the calendars in the UI show this month and last month.

I have clarified the help page to indicate that this is the date picker UI, and not the default date range of Workspace panels. Changes should be live this evening. Thanks!
